Name: SettingsService
Type: FolderType
Children:
- Class: Reference
  Type: HasOwnedType
  Target: g=277cad7344b13cd773c4c6fd79df0f02
- Class: Reference
  Type: HasOwnedType
  Target: g=1148590b9e766713c470353168761dea
- Class: Reference
  Type: HasOwnedType
  Target: g=d4f872d1dabe8140c331748a91af398b
- Class: Reference
  Type: HasOwnedType
  Target: g=57db62a2ebe6b1fddbbd7925c654f1e1
- Class: Reference
  Type: HasOwnedType
  Target: g=8e827a9dc61e074639fc776212260c60
- Class: Reference
  Type: HasOwnedType
  Target: g=2a40981c22528d0e23006fadcb6dd170
