Name: SettingsService
Type: FolderType
Children:
- Class: Reference
  Type: HasOwnedType
  Target: g=907b3161d23951335a1dd620845644c9
- Class: Reference
  Type: HasOwnedType
  Target: g=3a16d53666bf811c80247641ee330653
- Class: Reference
  Type: HasOwnedType
  Target: g=0e5deea1e0165dfd8fa5604ecf019d2e
- Class: Reference
  Type: HasOwnedType
  Target: g=51892d745a922635bd6d9a00d07f8965
- Class: Reference
  Type: HasOwnedType
  Target: g=4835713fdf0cd3a047df5580e6f4278a
- Class: Reference
  Type: HasOwnedType
  Target: g=f043b76c96ca640f17e681d5a19b1c95
